name: tests

on: [push, pull_request]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        numpy-version: [1.21.6, 1.22.4, 1.23.3]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install numtypes
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import numtypes, os; print(os.path.dirname(numtypes.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  numpy-main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        pushd .
        cd ..
        git clone --shallow-submodules --recurse-submodules --depth 1 https://github.com/numpy/numpy.git
        cd numpy
        # We have a shallow clone of the main branch of NumPy, which has no
        # git tags.  The code in versioneer.py requires a tag to create a
        # version, so create a tag with a blatantly fake version number.
        git config user.email "foo@example.com"
        git config user.name "Foo"
        git tag -a v999.0.0 -m "NumPy main development branch"
        python -m pip install .
        popd
    - name: Install numtypes
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import numtypes, os; print(os.path.dirname(numtypes.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  macos-11:
    runs-on: macos-11
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        numpy-version: [1.21.6, 1.22.4, 1.23.1]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install numtypes
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import numtypes, os; print(os.path.dirname(numtypes.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION
