name: tests

on: [push, pull_request]

jobs:
  test-released-numpy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
        numpy-version: [1.17.5, 1.18.5, 1.19.4, 1.20.3]

    steps:
    - uses: actions/checkout@v1
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install numpy==${{ matrix.numpy-version }}
    - name: Install numtypes
      run: |
        pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import numtypes, os; print(os.path.dirname(numtypes.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  test-nightly-numpy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install --pre --upgrade --timeout=60 -i https://pypi.anaconda.org/scipy-wheels-nightly/simple numpy
    - name: Install numtypes
      run: |
        python setup.py install
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import numtypes, os; print(os.path.dirname(numtypes.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION
