name: tests

on: [push, pull_request]

jobs:
  py-np-os-matrix:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        numpy-version: [1.21.6, 1.22.4, 1.23.5]
        os: [ubuntu-latest, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade setuptools==59.8.0
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install numtypes
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import numtypes, os; print(os.path.dirname(numtypes.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  py3-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
        numpy-version: [1.23.5]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade setuptools==59.8.0
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install numtypes
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import numtypes, os; print(os.path.dirname(numtypes.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  numpy-main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade setuptools==59.8.0
        python -m pip install pytest
        pushd .
        cd ..
        git clone --shallow-submodules --recurse-submodules --depth 1 https://github.com/numpy/numpy.git
        cd numpy
        # We have a shallow clone of the main branch of NumPy, which has no
        # git tags.  The code in versioneer.py requires a tag to create a
        # version, so create a tag with a blatantly fake version number.
        git config user.email "foo@example.com"
        git config user.name "Foo"
        git tag -a v999.0.0 -m "NumPy main development branch"
        python -m pip install .
        popd
    - name: Install numtypes
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import numtypes, os; print(os.path.dirname(numtypes.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION
