name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        numpy-version: [1.16, 1.17]

    steps:
    - uses: actions/checkout@v1
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependences
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install numpy==${{ matrix.numpy-version }}
    - name: Install numtypes
      run: |
        pip install .
    - name: Test with pytest
      run: |
        python -m pytest `python -c "import numtypes, os; print(os.path.dirname(numtypes.__file__))"`
